name: Release updated

on:
  push:
    branches:
      - swati/updateImages

jobs:
  BuildDockerImage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Login to Github Packages
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
  
    # - uses: codfish/semantic-release-action@master
    #   id: semantic
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    # - name: Build docker merkle-tree image
    #   run: docker build ./merkle-tree

    # - run: echo ${{ steps.semantic.outputs.release-version }}

    - name: Build and push UI docker image
      uses: docker/build-push-action@v2
      with:
        context: ./merkle-tree
        build-args: |
          GPR_TOKEN=${{ secrets.GPR_TOKEN }}
        tags: |
          ghcr.io/eyblockchain/timber-updated:latest
        # username: ${{ github.actor }}
        # password: ${{ secrets.GITHUB_TOKEN }}
        push: true
  ScanImage:
      name: Aquasec scan
      runs-on: ubuntu-latest
      needs: [BuildDockerImage]
      steps:
        - name: Trigger Aquascan Image Scan
          uses: convictional/trigger-workflow-and-wait@v1.6.1
          with:
            owner: ${{ github.repository_owner }}
            repo: saas-platform-iac-automation
            github_token: ${{ secrets.GPR_TOKEN_WITH_WORKFLOW_RIGHT }}
            workflow_file_name: image-scan-workflow.yml
            ref: master
            wait_interval: 11
            propagate_failure: true
            trigger_workflow: true
            wait_workflow: true
            client_payload: '{"image": "ghcr.io/eyblockchain/timber-updated:latest"}