name: Release

on:
  push:
    branches:
      - fabio/connection-resilience

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    # - uses: codfish/semantic-release-action@master
    #   id: semantic
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    # - name: Build docker merkle-tree image
    #   run: docker build ./merkle-tree

    # - run: echo ${{ steps.semantic.outputs.release-version }}

    - name: Build and push UI docker image
      uses: docker/build-push-action@v2
      with:
        context: ./merkle-tree
        file: ./Dockerfile
        build-args: |
          GPR_TOKEN=${{ secrets.GPR_TOKEN }}
        tags: |
          ${{ secrets.GHCR_REGISTRY }}/eyblockchain/timber/timber-multicontract:$RELEASE_VERSION
          ${{ secrets.GHCR_REGISTRY }}/eyblockchain/timber/timber-multicontract:latest
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        push: true
